Chrome no longer supports caretPositionFromPoint
Attempting to run document.caretPositionFromPoint in Chrome 65.0x gives the error "Uncaught TypeError: document.caretPositionFromPoint is not a function"