Safari does not support "DataTransfer() constructor".
I manually tested it on Safari 13.0.4 by calling "new DataTransfer()" in the console.

Output:
> TypeError: function is not a constructor (evaluating 'new DataTransfer()')